# site settings
title: Niñez Constituye
email: vigilantesporlainfancia@gmail.com
description: 'Niñez Constituye es un proyecto de seguimiento...'
baseurl: '//leymarco.ciudadaniai.org/' # the subpath of your site, e.g. /blog/
url: 'http://leymarco.ciudadaniai.org' # the base hostname & protocol for your site
# analytics: 'UA-102841648-2' # google analytics tracking code
launched: true
# build settings
markdown: kramdown
# notas y cosas finales
final_mark: 5.3
final_percentage: 40
